### ISSUE TITLE
SPIKE: Investigate the ODH CD process (Argo-CD, Operator new version, internal ODH and MOC)

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/opendatahub-operator#33]
Deliverable is documentation

**Comment by accorvin** [comment]
We have started using ArgoCD and Kustomize to deploy internal DH services. We've already implemented it for JupyterHub. It successfully deploys the ODH CR for JupyterHub, as well as our customizations for the deployment. We did extensive research before settling on this decision, and think it should be the standard for the ODH (I think this aligns well with the existing ODH plans since ODH has already started using Kustomize). 

You can find our application definitions here: https://github.com/AICoE/aicoe-sre and our automation for the ArgoCD deployment here: https://github.com/AICoE/aicoe-cd

I'm unsure of how to move forward. At some point in the next few months we will naturally get to the point where we start using ArgoCD to automate deployment (and upgrades) of the ODH operator itself. I think we'd probably start doing this maybe come September (but that is just a guess). Does that timeline align with the ODH roadmap's needs?

**Comment by crobby** [comment]
![ODH Continuous Deployment](https://user-images.githubusercontent.com/889317/91457213-1b3a7680-e852-11ea-9e69-4dfe90d78b8b.png)

**Comment by accorvin** [comment]
cc @anishasthana
