### ISSUE TITLE
Created operator group from odh-common created issues when operators are installed previously

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/opendatahub-operator#45]
We create an operator group in odh-common to be able to subscribe to the different operators included in ODH. In this specific use case it causes issues with multiple operator groups.
1. Create a new namespace
2. Install any operator from the catalog
3. Check to see there is an olm generated operator group in this namespace
4. Create a kfdef for ODH
5. check and see two operator groups which will cause failures

**Comment by keithfenechgig** [comment]
Same issue for me

**Comment by guimou** [comment]
That's kind of a blocker. It means you cannot deploy any other operator-base workload in a project where odh is, or forces you to create its own namespace for an odh deployment. Maybe not an issue in a simple deployment, but in a shared cluster with multiple ODH deployments (which is the goal of multi-namespace operator) it means that users must create at least 2 projects. One for their ODH instance, and one for the rest.
As it took me some time to figure this out, I would advise that until this bug is resolved there should be a not in the Doc or in the Operator description stating that you must not deploy/use any other operator in a namespace where ODH is deployed.
