### ISSUE TITLE
Add Kite to JupyterHub

### ISSUE THREAD

**Issue by durandom** [opendatahub-io/opendatahub-operator#49]
Not sure if this is the right repo for such an issue, I haven't found our JupyterHub repo :(

It would be great to get https://www.kite.com/integrations/jupyterhub/ added as a plugin. The free version runs locally and we could ask them to contribute the integration.

**Comment by vpavlin** [comment]
After an email discussion with the Kite authors we agreed it is not a good fit for ODH since it is not open source. That does not prevent the users from installing and using Kite. We might come back to this in the future or come up with some cooperation which would not require ODH to install Kite by default.
