### ISSUE TITLE
Changes to custom overlays made in git do not get propogated to deployments

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/opendatahub-operator#88]
**Describe the bug**
We use custom overlays that are located in another repo. When making changes to these and pushing them to get, we notice that the ODH operator will not pick up these changes as it already has the manifests cached. Current work around is to delete the ODH pod so that it fetches the new manifests from git and rebuilds the cache. 

**To Reproduce**
1. In a separate repo from `odh-manifests` add an overlay to an odh components (e.g. odh-dashboard) 
2. Add an overlay to that component in this repo and push it to github
3. Add this repo and overlay to the kfdef
4. Deploy this kfdef 
5. Now make a change to the overlay and push it again to git (e.g. an image tag to a deployment) 
6. Notice that the change hasn't propogated to the deployed resources 
7. Delete ODH pod, the change should now appear within the component 

**Expected behavior**
When I push a change to an kfdef's overlay in git, I expect the changes to propogate onto the deployments in the live cluster.

**Comment by tumido** [comment]
Just to add to that: repos in KfDef can point to either tag or a branch. If it points to a branch which is a moving target - the above happens. This is a flaw in `kfctl` which build the local cache in the current working directory in `.cache` folder and never updates it, if it doesn't need to. Can we make the operator either to clean up the cache periodically or not cache the manifests at all?

**Comment by vpavlin** [comment]
It is not that it "never updates" the cache. It does not update the cache without a reason - and I believe that a remote change is not a reason:)

We had a lengthy discussion about this with kfctl devs some time ago and came to conclusion that cache update should happen at 2 occasions:

1. A resource tracked by an operator is deleted (https://github.com/kubeflow/kfctl/blob/master/pkg/controller/kfdef/kfdef_controller.go#L281)
2. KFdef changes (https://github.com/kubeflow/kfctl/blob/master/pkg/controller/kfdef/kfdef_controller.go#L323)

If either of those happen, the whole dir representing the deployment (basically .cache and kustomize) is removed and recreated.

The operator does not really reconcille regularly (IIUC) - it watches all the resources and if any of them changes, it'll run reconcilation - KF operator devs thought that is better since there is too many resources to reconcile and it would be impossible to set a reasonable timing.

So a solution to your problem might just be to have a label or annotation which you bump on a change in your branch.

I believe that for prod deployments we should not pull from branches, but from tags, so any change would result in a new release of manifests which would result in a change in KFDef repo ref, which would result in reconcilation. This way we keep control in our hands.

Deploying from branch is fine for development/experimentation, so even deleting the pod is ok-ish workaround for such cases - but as I said above - it is not necessary.

I am going to close this issue, as I don't believe it is an actual issue, but feel free to reopen if you think otherwise.

**Comment by HumairAK** [comment]
Well, I understand the reasons. Technical limitations aside, IMO the rest seems like a strangely heavily opinionated stance.

> I believe that for prod deployments we should not pull from branches, but from tags

As we are applying a gitops model and changes come extremely frequently, this may result in creating a rather large number of tags regularly (adding topics, dashboards, datasources, etc.). This certainly maybe your opinion, but is it a general rule of GitOps? If the answer is no, then why force your users to follow this methodology? If the answer is yes, I would be interested in any documentation/reading material you may be able to forward us.

**Comment by vpavlin** [comment]
Maybe our understanding of GitOps differs - I believe the main reason for GitOps is to make sure that everything is tracked in Git and I can say in any moment which specific version (commit) is deployed. I don't see GitOps flying well with the "moving target" which a branch represents.

Quick google search tells me:

> #2. The canonical desired system state versioned in Git.
> With the declaration of your system stored in a version control system, and serving as your canonical source of truth, you have a single place from which everything is derived and driven. This trivializes rollbacks; where you can use a `Git revert` to go back to your previous application state. With Git’s excellent security guarantees, you can also use your SSH key to sign commits that enforce strong security guarantees about the authorship and provenance of your code.  

My experience with GitOps years ago was that our goal was to 1. have a precise track record of changes, 2. be able to quickly see what version (commit) is deployed.

If I map this to your case - I would say feel free to pull from a branch, but make sure your system adds a particular commit somewhere - a label or an annotation - this way you have tracking of what is deployed and the change to KFDef triggers a redeployment.

It seems to me that there might also be a mismatch in our understanding of where the GitOps start - it sounds to me like you are saing the operator is the GitOps tool. But I think the GitOps tool should use the operator - think about standard way how operators work - all the manifests are baked into the operator image, so if you want to change them, you need to rebuild and redeploy the operator and potentially still update the CR to match the new version of the operator.

With ODH operator you just need to change manifests and make sure KFDef is modified for the operator to know it has to perform an update.

I am happy to talk more!

Also..Sorry if my response sounded too opinionated:) In my mind, this was not something that could cause "confusion"
